In [1]:
import os, glob
import json
import pandas as pd
import numpy as np
from ast import literal_eval

In [2]:
os.chdir("../GYAFC_Corpus/Family_Relationships/train/")
os.listdir()

['formal', 'informal']

In [3]:
with open('formal', 'r', encoding='UTF-8') as file:
    flines1 = file.readlines()
    flines1 = [line.rstrip() for line in flines1]

print(len(flines1))
print(flines1[0])

51967
I prefer to let the guy ask me.


In [4]:
with open('informal', 'r', encoding='UTF-8') as file:
    ilines1 = file.readlines()
    ilines1 = [line.rstrip() for line in ilines1]

print(len(ilines1))
print(ilines1[0])

51967
Sure, it's ok, but I always have let the guy ask me.


In [5]:
print(flines1[0])
print(ilines1[0])

I prefer to let the guy ask me.
Sure, it's ok, but I always have let the guy ask me.


In [6]:
os.chdir("../..//Entertainment_Music/train/")
os.listdir()

['formal', 'informal']

In [7]:
with open('formal', 'r', encoding='UTF-8') as file:
    flines2 = file.readlines()
    flines2 = [line.rstrip() for line in flines2]

print(len(flines2))
print(flines2[0])


with open('informal', 'r', encoding='UTF-8') as file:
    ilines2 = file.readlines()
    ilines2 = [line.rstrip() for line in ilines2]

print(len(ilines2))
print(ilines2[0])

52595
The In-Laws movie isn't a holiday movie, but it's okay.
52595
the movie The In-Laws not exactly a holiday movie but funny and good!


In [8]:
print(len(flines1))
flines1.extend(flines2)
print(len(flines1))

51967
104562


In [9]:
print(len(ilines1))
ilines1.extend(ilines2)
print(len(ilines1))

51967
104562


In [10]:
df= pd.DataFrame(list(zip(ilines1, flines1)), columns=['informal_0', 'formal_1'])
df

informal_0  \
0       Sure, it's ok, but I always have let the guy a...   
1       Hmmm, I'm a guy suffering from verbal abuse fr...   
2          You will have more friends that you want... ;)   
3       It's nice, you get to see pictures of who you ...   
4                                I NEED TO KNOW WHAT 2 DO   
...                                                   ...   
104557  Amzing,Hilarouus plz sendur id so i can add u ...   
104558  Go to yahoo.com then click on music and type i...   
104559    hell yea shave that shit please     or try nair   
104560  she grew up to become an evil old person who r...   
104561  I have it if you would like it... message me a...   

                                                 formal_1  
0                         I prefer to let the guy ask me.  
1             I suffer through verbal abuse from my wife.  
2               You will have more friends than you want.  
3       It's nice that you get to see pictures of who ...  
4                              I need to know what to do.  
...                                                   ...  
104557  This is amazing and funny. Please send your id...  
104558  Visit yahoo.com, and click on music. From ther...  
104559                          Please shave or try nair.  
104560  She grew up to be a bad person, who rapes youn...  
104561  I do have it. Please send me a message and I w...  

[104562 rows x 2 columns]

# sbert

In [11]:
!pip install -U sentence_transformers

In [12]:
smodel="paraphrase-albert-small-v2"
from sentence_transformers import SentenceTransformer
modelS = SentenceTransformer(smodel)

Downloading: 100%|██████████| 190/190 [00:00<00:00, 94.9kB/s]
Downloading: 100%|██████████| 4.03k/4.03k [00:00<00:00, 4.02MB/s]
Downloading: 100%|██████████| 122/122 [00:00<00:00, 122kB/s]
Downloading: 100%|██████████| 46.7M/46.7M [00:00<00:00, 47.5MB/s]
Downloading: 100%|██████████| 53.0/53.0 [00:00<00:00, 26.5kB/s]
Downloading: 100%|██████████| 245/245 [00:00<00:00, 122kB/s]
Downloading: 100%|██████████| 760k/760k [00:00<00:00, 42.2MB/s]
Downloading: 100%|██████████| 1.31M/1.31M [00:01<00:00, 671kB/s] 
Downloading: 100%|██████████| 229/229 [00:00<00:00, 114kB/s]


In [14]:
informal=df['informal_0'].tolist()
formal=df['formal_1'].tolist()

In [24]:
len(informal)

104562

In [25]:
from tqdm import tqdm
lst=[]
for i, doc in tqdm(enumerate(informal), total=len(informal)):
    lst.append(modelS.encode(str(doc), convert_to_tensor=True))

100%|██████████| 104562/104562 [25:54<00:00, 67.24it/s]


In [26]:
lst1=[]

In [27]:
for i, doc in tqdm(enumerate(formal), total=len(formal)):
    lst1.append(modelS.encode(str(doc), convert_to_tensor=True))

100%|██████████| 104562/104562 [28:06<00:00, 62.01it/s]


In [28]:
len(lst)

104562

In [29]:
len(lst[0])

768

In [30]:
len(lst1)

104562

In [31]:
import os

In [32]:
os.getcwd()

'd:\\OneDrive - Indian School of Business\\Desktop\\TST_CycleGAN\\GYAFC_Corpus\\Entertainment_Music\\train'

In [33]:
os.chdir(r"d:\\OneDrive - Indian School of Business\\Desktop\\TST_CycleGAN\data")

In [34]:
df.to_csv('gyfac.csv', index=False)
df.head()

informal_0  \
0  Sure, it's ok, but I always have let the guy a...   
1  Hmmm, I'm a guy suffering from verbal abuse fr...   
2     You will have more friends that you want... ;)   
3  It's nice, you get to see pictures of who you ...   
4                           I NEED TO KNOW WHAT 2 DO   

                                            formal_1  
0                    I prefer to let the guy ask me.  
1        I suffer through verbal abuse from my wife.  
2          You will have more friends than you want.  
3  It's nice that you get to see pictures of who ...  
4                         I need to know what to do.

In [35]:
from sentence_transformers import util

In [37]:
similarity = util.cos_sim(lst[0], lst1[0])
print(similarity)

tensor([[0.7161]])


In [38]:
similarity = util.cos_sim(lst[0], lst1[1])
print(similarity)

tensor([[0.2459]])


In [39]:
similarity = util.cos_sim(lst[0], lst1[4])
print(similarity)

tensor([[0.2898]])


In [40]:
import pickle

with open('informal.pickle', 'wb') as pkl:
    pickle.dump(lst, pkl)

with open('formal.pickle', 'wb') as pkl:
    pickle.dump(lst1, pkl)